export const ACTIONS = {
  FETCH_TODO: 'FETCH_TODO',
  FETCH_TODO_FAILED: 'FETCH_TODO_FAILED',
  FETCH_TODO_SUCCESSED: 'FETCH_TODO_SUCCESSED',
  ADD_TODO: 'ADD_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  SAVE_TODO: 'SAVE_TODO',
  CHANGE_LOADING_STATUS: 'CHANGE_LOADING_STATUS',
}